name: CI/CD Lambda

on:
  push:
    branches:
      - main
      - master
      - develop

  pull_request:

env:
  JAVA_VERSION: "21"

permissions:
  contents: read

jobs:

  # ============================================================
  # 1. SECURITY - OWASP
  # ============================================================

  security:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Setup Java
        uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3 # v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Restore OWASP cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: ${{ runner.os }}-owasp-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-owasp-

      - name: OWASP Dependency Check
        run: mvn --no-transfer-progress dependency-check:check
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}


  # ============================================================
  # 2. BUILD + TEST + COVERAGE + SONARCLOUD
  # ============================================================

  quality:
    name: Build, Tests, Coverage and SonarCloud
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Setup Java
        uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3 # v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Build and test
        run: mvn --no-transfer-progress clean verify

      - name: Verify JAR
        run: |
          echo "Generated JAR:"
          ls -lh target/*.jar

      - name: Verify JaCoCo
        run: |
          test -f docs/security/jacoco/jacoco.xml

          echo "JaCoCo report:"
          ls -lh docs/security/jacoco/jacoco.xml

      - name: SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn --no-transfer-progress sonar:sonar \
            -Dsonar.projectKey=michaelhion_oficina360_lambda \
            -Dsonar.organization=michaelhion \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.coverage.jacoco.xmlReportPaths=docs/security/jacoco/jacoco.xml
